USE master;

IF EXISTS (SELECT name FROM sys.databases WHERE name = N'SportsCalendar')
    DROP DATABASE SportsCalendar;

CREATE DATABASE SportsCalendar;

USE SportsCalendar;

CREATE TABLE Sports (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    Name VARCHAR(100) NOT NULL UNIQUE,
    CreatedAt DATETIME2 DEFAULT GETUTCDATE(),
    UpdatedAt DATETIME2 DEFAULT GETUTCDATE()
);

CREATE TABLE Countries (
    Code CHAR(3) PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    CreatedAt DATETIME2 DEFAULT GETUTCDATE()
);

CREATE TABLE Competitions (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    Slug VARCHAR(255) NOT NULL UNIQUE,
    SportId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Sports(Id) NOT NULL,
    CreatedAt DATETIME2 DEFAULT GETUTCDATE(),
    UpdatedAt DATETIME2 DEFAULT GETUTCDATE()
);

CREATE TABLE Stages (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    Ordering INT NOT NULL,
    CreatedAt DATETIME2 DEFAULT GETUTCDATE()
);

CREATE TABLE Stadiums (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    CountryCode CHAR(3) FOREIGN KEY REFERENCES Countries(Code),
    CreatedAt DATETIME2 DEFAULT GETUTCDATE()
);

CREATE TABLE Teams (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    OfficialName VARCHAR(255) NOT NULL,
    Slug VARCHAR(255) NOT NULL UNIQUE,
    Abbreviation CHAR(5) NOT NULL,
    CountryCode CHAR(3) FOREIGN KEY REFERENCES Countries(Code),
    SportId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Sports(Id) NOT NULL,
    StagePosition TINYINT NULL CHECK (StagePosition >= 1),
    CreatedAt DATETIME2 DEFAULT GETUTCDATE(),
    UpdatedAt DATETIME2 DEFAULT GETUTCDATE()
);

CREATE INDEX IX_Teams_SportId ON Teams(SportId);

CREATE INDEX IX_Teams_Slug ON Teams(Slug);

CREATE TABLE Events (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    Name VARCHAR(500) NOT NULL,
    Description VARCHAR(2000) NULL,
    Season INT NOT NULL,
    Status VARCHAR(50) NOT NULL CHECK (Status IN('scheduled', 'cancelled', 'playing', 'played')),
    TimeVenueUTC TIME NOT NULL,
    DateVenueUTC DATE NOT NULL,
    GroupName VARCHAR(255) NULL,
    HomeTeamId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Teams(Id),
    AwayTeamId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Teams(Id),
    StadiumId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Stadiums(Id) ON DELETE SET NULL,
    StageId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Stages(Id),
    CompetitionId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Competitions(Id) NOT NULL,
    CreatedAt DATETIME2 DEFAULT GETUTCDATE(),
    UpdatedAt DATETIME2 DEFAULT GETUTCDATE()
);

CREATE INDEX IX_Events_DateVenueUTC ON Events(DateVenueUTC);

CREATE INDEX IX_Events_Status ON Events(Status);

CREATE INDEX IX_Events_CompetitionId ON Events(CompetitionId);

ALTER TABLE Events 
ADD CONSTRAINT CHK_HomeAwayDifferent CHECK (HomeTeamId <> AwayTeamId);

CREATE TABLE Results (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    EventId UNIQUEIDENTIFIER NOT NULL UNIQUE FOREIGN KEY REFERENCES Events(Id) ON DELETE CASCADE,
    WinnerId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Teams(Id) NULL,
    Message VARCHAR(1000) NULL,
    CreatedAt DATETIME2 DEFAULT GETUTCDATE(),
    UpdatedAt DATETIME2 DEFAULT GETUTCDATE()
);

CREATE TABLE PeriodScores (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    ResultId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Results(Id) ON DELETE CASCADE,
    PeriodNumber TINYINT NOT NULL,
    HomeScore TINYINT NOT NULL,
    AwayScore TINYINT NOT NULL,
    CreatedAt DATETIME2 DEFAULT GETUTCDATE()
);

CREATE TABLE MatchIncidents (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    ResultId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Results(Id) NOT NULL,
    TeamId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Teams(Id),
    IncidentType VARCHAR(50) NOT NULL CHECK (IncidentType IN('goal', 'yellowCard', 'secondYellowCard', 'redCard', 'instantRedCard')),
    MatchMinute INT NULL,
    CreatedAt DATETIME2 DEFAULT GETUTCDATE()
);
